/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.jackhenry;

import java.io.PrintWriter;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "neatlang", description = "neatlang compiler")
public class CLI implements Callable<Integer> {

    @Option(names = { "-c", "--class" })
    private String classFilePath;

    @Override
    public Integer call() throws Exception {
        PrintWriter printWriter = new PrintWriter(System.out);
        AsmifierWrapper.asmify(classFilePath, printWriter);
        return 0;
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new CLI()).execute(args);
        System.exit(exitCode);
    }
}
